name: Java CI with Maven

#Event trigger
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Artifact versioning
      run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit

    - name: Push Patch Version
      run: |
        git config --global user.email "yarinchanan@gmail.com"
        git config --global user.name "YarinChanan"
        git add pom.xml
        git commit -m "Update version in pom.xml"
        git push origin master

     # Build Docker Image

    - name: Build Docker Image
      run: |
          DOCKER_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) && docker build -t yarinch/hello_world:${DOCKER_VERSION} -t yarinch/hello_world:latest .

      # Login to Docker registry
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Docker Image (if Dockerfile exists)
    - name: Push Docker Image
      run: |
        DOCKER_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        docker push yarinch/hello_world:${DOCKER_VERSION}
        docker push yarinch/hello_world:latest


    - name: Deploy image
      run: |
          DOCKER_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY2 }} ubuntu@100.24.20.181 && sudo docker pull yarinch/hello_world:${DOCKER_VERSION} && sudo docker run -d yarinch/hello_world:${DOCKER_VERSION}"
