name: Java CI with Maven

#Event trigger
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

          # Build Docker Image
      - name: Build Docker Image
        run: docker build -t my-java-app:latest .

      # Login to Docker registry
      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Docker Image (if Dockerfile exists)
      - name: Push Docker Image
        run: docker push yarinch/hello_world:latest
